server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://172.30.1.81:3306/assert?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#   type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#172.30.1.81
#192.168.80.109